theme: jekyll-theme-cayman

# Site settings
title: seif.codes
description: Your blog description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seif.codes" # the base hostname & protocol for your site
twitter_username: seiflotfy
github_username:  seiflotfy

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

disqus_shortname: seiflotfy